name: Verify Build Workflow
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Comment tests results
        if: always()
        run: |
          PULL_REQ_ID=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          PULL_REQ_URL=https://api.github.com/repos/${{ github.repository }}/issues/$PULL_REQ_ID/comments
          curl --request POST \
          --url $PULL_REQ_URL \
          --header "authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          --header "content-type: application/json" \
          -d "@tests_results.json"